# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

#TODO: CHANGE THESE CREDENTIALS
development:
  adapter: postgresql
  database: ultrakast
  host: localhost
  pool: 5
  timeout: 5000
  #username: root
  username: postgres
  password: postgres
