#access_key_id: AKIAJQZXH5S5KISCGKQA
#secret_access_key: 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
#bucket: ultrakast

access_key_id: AKIAIDPZ4UCBCSI6WOYQ
secret_access_key: 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
bucket: ultrakast-dev